import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Header from "@/components/Header";
=======
>>>>>>> a4a3aaa (Initial commit from Create Next App)

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Walmart Clone",
  description: "Created by daemon",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> a4a3aaa (Initial commit from Create Next App)
};

export default function RootLayout({
  children,
<<<<<<< HEAD
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className="flex">
          {modal}
          {children}
        </div>
        
        </body>
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
>>>>>>> a4a3aaa (Initial commit from Create Next App)
    </html>
  );
}
